specfile_path: ansible-lint.spec
actions:
  create-archive:
    - "python3 setup.py sdist --dist-dir ."
    - "sh -c 'echo ansible-lint-$(python3 setup.py --version).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"
  post-upstream-clone:
    - |
      bash -c "sed -i -e 's/Version: VERSION_PLACEHOLDER/Version: $(python3 setup.py --version)/' ansible-lint.spec"
jobs:
  - job: copr_build
    metadata:
      targets:
        - centos-stream-x86_64
        - fedora-stable
    trigger: pull_request
  # - job: tests
  #   trigger: pull_request
  #   metadata:
  #     targets:
  #     - fedora-all
  # - job: propose_downstream
  #   trigger: release
  #   metadata:
  #     dist-git-branch: master
